// Writes docs/barrier-log.md: one line per barrier section with its s range, side, type and the reason it exists.
// A section with no reason fails the audit (tools/audit.js). Run with `npm run barrierlog`.
import { writeFileSync } from 'node:fs';
import { buildTrack, BARRIER } from '../src/track.js';

const T = buildTrack(), names = Object.fromEntries(Object.entries(BARRIER).map(([k, v]) => [v, k.toLowerCase()]));
const lines = T.barriers.map(b => {
  const s0 = T.s[b.pts[0][3]], s1 = T.s[b.pts.at(-1)[3]];
  let len = 0; for (let i = 1; i < b.pts.length; i++) len += Math.hypot(b.pts[i][0] - b.pts[i - 1][0], b.pts[i][2] - b.pts[i - 1][2]);
  return { s0, s1, side: b.side ? 'R' : 'L', type: names[b.type] + (b.hidden ? ' (hidden)' : ''), len, why: b.why || 'NO REASON' };
}).sort((a, c) => a.s0 - c.s0);
let md = '# Barrier log\n\nGenerated by `npm run barrierlog`. One line per section: where, which side, what, and why it is there. A section with no reason is a bug.\n\n| s from | s to | side | type | length m | reason |\n|---|---|---|---|---|---|\n';
for (const l of lines) md += `| ${l.s0.toFixed(0)} | ${l.s1.toFixed(0)} | ${l.side} | ${l.type} | ${l.len.toFixed(0)} | ${l.why} |\n`;
writeFileSync(new URL('../docs/barrier-log.md', import.meta.url), md);
console.log(`${lines.length} barrier sections logged`);
