// The optional racing line: a ribbon painted on the road along the reference lap in racingLineData.js (generated by
// `npm run racingline` from the real autopilot lap). Green: you can be on the throttle. Yellow: lift. Red: brake.
//
// One mesh. The vertices are the whole lap (4 per sample: a faded outer edge and a solid inner edge on each side); the
// index buffer runs in lap order and repeats the first quads after the last, so a draw range of "40 m behind to 350 m
// ahead" is always one contiguous range, also across the start line.

import * as THREE from 'three';
import data from './racingLineData.js';

export const RACING_LINE_LEGEND = {
  green: 'Green: you can be on the throttle',
  yellow: 'Yellow: lift off the throttle',
  red: 'Red: brake',
};

export const LINE_WIDTH = 0.9;       // metres, edge to edge
const CORE = 0.5;                    // solid part of the width, metres
const DECAL = 0.006;                 // same lift as the paint decals in trackMesh.js
const BEHIND = 40, AHEAD = 350;      // metres of line drawn behind and ahead of the car
const BLEND = 4;                     // metres to blend between classes
const OPACITY = 0.75;
export const CLASS_COLOURS = { t: 0x37d67a, l: 0xffd23f, b: 0xff4d4d };

// Per-sample colour (linear RGB, 3 floats a sample) with a BLEND-metre blend between classes (a box filter over BLEND m).
export function blendColours(classes, ds, blend = BLEND) {
  const n = classes.length, out = new Float32Array(n * 3);
  const base = {};
  for (const k in CLASS_COLOURS) { const c = new THREE.Color(CLASS_COLOURS[k]); base[k] = [c.r, c.g, c.b]; }
  const half = Math.max(0, Math.round(blend / ds / 2));
  for (let i = 0; i < n; i++) {
    let r = 0, g = 0, b = 0, m = 0;
    for (let k = -half; k <= half; k++) {
      const c = base[classes[(i + k + n * 2) % n]];
      r += c[0]; g += c[1]; b += c[2]; m++;
    }
    out[i * 3] = r / m; out[i * 3 + 1] = g / m; out[i * 3 + 2] = b / m;
  }
  return out;
}

// Which quads to draw. Quad k joins sample k and k+1 (mod n); the index buffer holds n + extra quads in lap order.
// Returns { first, count } in quads, first in [0, n); first + count never passes n + extra.
export function visibleRange(carS, length, n, behind = BEHIND, ahead = AHEAD) {
  const ds = length / n;
  const s = ((carS % length) + length) % length;
  let first = Math.floor((s - behind) / ds);
  first = ((first % n) + n) % n;
  const count = Math.min(n, Math.ceil((behind + ahead) / ds) + 1);
  return { first, count };
}
export const extraQuads = (n, length) => Math.min(n, Math.ceil((BEHIND + AHEAD) / (length / n)) + 2);

// The ribbon's vertices and the lap-ordered index buffer. `heightAt(x, z, i)` is T.groundAt.
export function buildLineGeometry(T, d, classes, heightAt = T.groundAt) {
  const n = d.length, per = 4;
  const pos = new Float32Array(n * per * 3), col = new Float32Array(n * per * 4);
  const rgb = blendColours(classes, T.ds);
  const w = [-LINE_WIDTH / 2, -CORE / 2, CORE / 2, LINE_WIDTH / 2], alpha = [0, 1, 1, 0];
  for (let i = 0; i < n; i++) {
    for (let k = 0; k < per; k++) {
      const e = d[i] + w[k];
      const x = T.x[i] + T.nx[i] * e, z = T.z[i] + T.nz[i] * e;
      const v = (i * per + k);
      pos[v * 3] = x; pos[v * 3 + 1] = heightAt(x, z, i) + DECAL; pos[v * 3 + 2] = z;
      col[v * 4] = rgb[i * 3]; col[v * 4 + 1] = rgb[i * 3 + 1]; col[v * 4 + 2] = rgb[i * 3 + 2]; col[v * 4 + 3] = alpha[k];
    }
  }
  const extra = extraQuads(n, T.length), total = n + extra;
  const index = new Uint32Array(total * 18);
  for (let q = 0; q < total; q++) {
    const a = (q % n) * per, b = ((q + 1) % n) * per;
    for (let s = 0; s < 3; s++) {
      const o = q * 18 + s * 6;
      index.set([a + s, b + s, a + s + 1, a + s + 1, b + s, b + s + 1], o);
    }
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute('position', new THREE.BufferAttribute(pos, 3));
  geo.setAttribute('color', new THREE.BufferAttribute(col, 4));
  geo.setIndex(new THREE.BufferAttribute(index, 1));
  return geo;
}

// A dataset that does not match the track (the layout changed and nobody ran `npm run racingline`) draws nothing.
export const dataMatches = (T, d = data) => d.d.length === T.N && Math.abs(d.length - T.length) < 0.05 && Math.abs(d.ds - T.ds) < 1e-4 && d.c.length === T.N;

export function createRacingLine(T) {
  const group = new THREE.Group();
  group.name = 'racing-line';
  group.visible = false;
  const ok = dataMatches(T);
  if (!ok) console.warn('Racing line data does not match this track: run `npm run racingline`.');
  let mesh = null, want = false;
  if (ok) {
    const geo = buildLineGeometry(T, data.d, data.c);
    const mat = new THREE.MeshBasicMaterial({
      vertexColors: true, transparent: true, side: THREE.DoubleSide, opacity: OPACITY, depthWrite: false, toneMapped: false,
      polygonOffset: true, polygonOffsetFactor: -4, polygonOffsetUnits: -8,
    });
    mesh = new THREE.Mesh(geo, mat);
    mesh.frustumCulled = false;     // the draw range changes every frame
    mesh.renderOrder = 2;
    mesh.userData.debug = 'line';
    mesh.castShadow = false; mesh.receiveShadow = false;
    group.add(mesh);
  }
  const api = {
    group, mesh,
    setVisible(on) { want = !!on && ok; group.visible = want; },
    update(carS) {
      if (!mesh || !want) return;
      const { first, count } = visibleRange(carS, T.length, T.N);
      mesh.geometry.setDrawRange(first * 18, count * 18);
    },
  };
  return api;
}
